name: Run test of application

on: 
  push: #Execute on commit to branch master
    branches:
      - master
  pull_request: #Execute on pull request to branch master
    branches:
      - master

jobs: 
  test_python:
    runs-on: ubuntu-latest #Docker image to base the work on 
    steps:
      - name: Set up Python 3.8
        uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      -name: Run unit tests
        run: |
          python -m pytest .\tests.py